import type { Metadata } from 'next';
import { Nunito_Sans, Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Entertainment Web App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
